// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhj2nQfCoSLQbupCOky9VG4qv481Fqz4',
    appId: '1:240632493418:web:8d0fc3d69a982dcccfe113',
    messagingSenderId: '240632493418',
    projectId: 'discover-app-955b7',
    authDomain: 'discover-app-955b7.firebaseapp.com',
    storageBucket: 'discover-app-955b7.firebasestorage.app',
    measurementId: 'G-8FZWK61WMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Zklp6jAgJ-waCSgHeMwIoJQRRT7k1Ec',
    appId: '1:240632493418:android:3986a6f20ee8da2ecfe113',
    messagingSenderId: '240632493418',
    projectId: 'discover-app-955b7',
    storageBucket: 'discover-app-955b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD61b4LlJNZRZZBUHrzgNBxuo_W8Zjlqlk',
    appId: '1:240632493418:ios:67c2e52c77b91a83cfe113',
    messagingSenderId: '240632493418',
    projectId: 'discover-app-955b7',
    storageBucket: 'discover-app-955b7.firebasestorage.app',
    iosClientId: '240632493418-mamml7k6k40ktambhsa900fvlr9r1kba.apps.googleusercontent.com',
    iosBundleId: 'com.discover.discover',
  );
}
